### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by qrah** [yomimono/ocaml-certify#24]
when compiling with:   (flags (-ccopt -static))

and then running it on a host with an older processor, certify crashes on illegal instruction:
    (flags (-ccopt -static))

traps: certify.exe[14886] trap invalid opcode ip:52b9fe sp:7fff05c3a4d8 error:0 in certify.exe[401000+291000]

**Comment by hannesm** [comment]
to get a certify which as well works on older machines, please set the environment variable `NOCRYPTO_ACCELERATE` to `false` while building nocrypto (a dependency of certify).

if you're using #23 the variable is `MIRAGE_CRYPTO_ACCELERATE`. and in the future, we plan to change this to load-time/run-time instead of build-time (see https://github.com/mirage/mirage-crypto/issues/45).
